### ISSUE TITLE
Update WPCS

### ISSUE THREAD

**Issue by brandonkal** [Automattic/phpcs-neutron-ruleset#2]
It would be nice to see how this config would fit in with WPCS 1.1.0.
They've made a lot of changes and moved sniffs around so this is a bit more complicated than looking at what was depreciated.

**Comment by sirbrillig** [comment]
Oh wow, I didn't realize there was a new version (or even that it hit 1.0!). Thanks for the notification.

**Comment by szepeviktor** [comment]
Now there is [2.0](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/releases).
